import Darwin
import Foundation

public protocol CodexRuntimeConnection: AnyObject {
    var runtimeVersion: String { get }
    var instanceID: String { get }
    var connected: Bool { get }
    var supportsExecutionModes: Bool { get }
    var onNotification: (@Sendable (String, Data) -> Void)? { get set }
    var onServerRequest: (@Sendable (Data, String, Data) -> Bool)? { get set }
    func request(_ method: String, params: Data) throws -> Data
    func respond(requestID: Data, result: Data) throws
    func disconnect()
}

extension CodexRuntimeConnection {
    public var connected: Bool { true }
    public var supportsExecutionModes: Bool { false }
    public var onServerRequest: (@Sendable (Data, String, Data) -> Bool)? {
        get { nil }
        set {}
    }
    public func respond(requestID: Data, result: Data) throws { throw RuntimeDriverError.unavailable }
}

public struct CodexManagedRuntimeConfiguration: Codable, Sendable {
    public var enabled: Bool
    public let executablePath: String
    public let directoryPath: String
    public init(enabled: Bool = false, executablePath: String, directoryPath: String) {
        self.enabled = enabled
        self.executablePath = executablePath
        self.directoryPath = directoryPath
    }
    public var socketPath: String { URL(fileURLWithPath: directoryPath).appendingPathComponent("control.sock").path }
    public var codexHomePath: String { URL(fileURLWithPath: directoryPath).appendingPathComponent("codex-home").path }
    public var loginArguments: [String] { [executablePath, "login"] }
    /// User-run command for a terminal or explicitly configured desktop SSH backend.
    /// Does not install SSH config/launchd or route ordinary This Mac sessions here.
    public var sharedProxyArguments: [String] { [executablePath, "app-server", "proxy", "--sock", socketPath] }
}

/// Exact native schema hashes generated by codex-cli 0.159.0, stable surface only.
/// Unsupported releases are closed until their schema and native evidence are reviewed.
public enum CodexManagedRuntimeContract {
    public static let version = "0.159.0"
    static let schemaHashes: [String: String] = [
        "v1/InitializeParams.json": "b55124e7c0f36a1789396daa5578217a92be67f053903696236686e59f6f212e",
        "v1/InitializeResponse.json": "62ad689c2cb6379913c1d72749cfd8de5089d35760214123518eb92eef11acc9",
        "v2/ThreadStartParams.json": "e9c6d3cc18d049bfbc0249add3808fb8e5a27e1a0b5a423767aafbc3859a9428",
        "v2/ThreadStartResponse.json": "70d9c9a3a064edb76662ec7cd066d142ed9252b768272bc3a7d00788386755c0",
        "v2/ThreadReadParams.json": "dfe040c6ac71d30795b8be3f3ff232e66f362a37f883b491e5d1ea367f470db4",
        "v2/ThreadReadResponse.json": "3a0aaf9cff80796d07130b85723ca825f9203796d15c878f452083cf9f9a6f0a",
        "v2/TurnStartParams.json": "2dfcf68705896fadc344ccfeb2e9fe5a6bcbbb8b9a90cf449ce232b636daf05a",
        "v2/TurnStartResponse.json": "12c5151421bb061297c9790ff795a44aa4b9bdb91fbb68012dcf0a08cf4198b1",
        "v2/TurnInterruptParams.json": "6dff382dae73d1dbc58406ed045605f647e7a49660e2540fbd2c6c24d60c5f2b",
        "CommandExecutionRequestApprovalParams.json":
            "16a71816c2d66e319c2c4aa83dd636dfdc43c61e72b6d5475e421ce08d8e6558",
        "CommandExecutionRequestApprovalResponse.json":
            "6d0767113e22f311381809b6b236b0dde2b99b01992879c26bf7b1ea0e003cb7",
        "FileChangeRequestApprovalParams.json": "13848b26814c286ad6425a20d01c1691c86790e1f9e2529399677a8a22fe0d18",
        "FileChangeRequestApprovalResponse.json": "b95b03ee6be674e25cee2e863cc135a28620e1070addd2f34685aadee27cde08",
        "ToolRequestUserInputParams.json": "fda15b62e7446105b59c8ed85c908abed2a47db70653e57c92c47a2f204fa77a",
        "ToolRequestUserInputResponse.json": "5073b245f741fa8ce62ec52e4dd1809b7831f9c4284c279a78abc9b171f8e3f2",
        "v2/GetAccountParams.json": "30b545275f60975b55bd6fbaafd70f15505801d14168ee82d3931b6e93c78aab",
        "v2/GetAccountResponse.json": "c3092dd8e52c2933c5ba5f0bf92377174f65bed627ff4ef5d7c04a189dd34fd1",
    ]
    public static func validateSchemaDirectory(_ directory: URL, runtimeVersion: String) throws {
        guard runtimeVersion == version else { throw RuntimeDriverError.incompatibleVersion }
        for (path, hash) in schemaHashes {
            let file = try FileHandle(forReadingFrom: directory.appendingPathComponent(path))
            defer { try? file.close() }
            let bytes = try file.read(upToCount: 2_097_153) ?? Data()
            guard bytes.count <= 2_097_152, RuntimeOperationLedger.hash(bytes) == hash
            else { throw RuntimeDriverError.incompatibleVersion }
        }
    }
    /// Generated independently with --experimental; stable schema checks remain mandatory.
    static let executionModeSchemaHashes: [String: String] = [
        "v2/CollaborationModeListParams.json": "20991b8d69722b301ef860307a4df89f20c475e4a4f1cd5212d6b71ab1507655",
        "v2/CollaborationModeListResponse.json": "d51cd5bd1b7cdf93a1a665adc333867ee12fa85ee811a873cb0131bf5d49d3e6",
        "v2/ModelListParams.json": "de29a536c00a5b8f46f34dba417dabd93365305571a8ed200e33bea85db68b5a",
        "v2/ModelListResponse.json": "bfbb3ee9f6e203e0b767587c17de94b9cb42f712d0d8168afbbbc3fcb4492f30",
        "v2/ThreadSettingsUpdateParams.json": "749419634bb7ed66216d72bf9d8734ecf0e6efaa8cd46fe51a117d1b42ed9657",
        "v2/ThreadSettingsUpdateResponse.json": "adb6c5232ff2474b61ac1811c9fe0faf8beae7f629c9bb2182190679d82bf0b1",
        "v2/ThreadSettingsUpdatedNotification.json": "5e0f512bcca5fbf3cfea9f13574928ad26e790d5bc765ea92cd024a7ac96f86e",
        "v2/TurnStartParams.json": "07771223642e1b61bd9aac0069fc0f98143a1c047724ca02c7ceb13653442738",
        "v2/ThreadStartResponse.json": "92f5ddc37717b922de1dc0b0405e9a6d463f370554e2091610c6e595bc2616d4",
        "v2/ThreadReadResponse.json": "2af6b987644cfb23e6f408f3cfb29e73ad6255ba2294366d36d56aeabe3854da",
    ]
    public static func validateExecutionModeSchemaDirectory(_ directory: URL, runtimeVersion: String) throws {
        guard runtimeVersion == version else { throw RuntimeDriverError.incompatibleVersion }
        for (path, hash) in executionModeSchemaHashes {
            let file = try FileHandle(forReadingFrom: directory.appendingPathComponent(path))
            defer { try? file.close() }
            let bytes = try file.read(upToCount: 2_097_153) ?? Data()
            guard bytes.count <= 2_097_152, RuntimeOperationLedger.hash(bytes) == hash
            else { throw RuntimeDriverError.incompatibleVersion }
        }
    }
}

/// Independent app-server over a private Unix socket. Only its proxy client belongs
/// to the gateway; disconnect/deinit never sends an interrupt or kills the server.
final class CodexSocketRuntimeConnection: CodexRuntimeConnection, @unchecked Sendable {
    private struct Metadata: Codable {
        let version: String
        let instanceID: String
        let executablePath: String
        let processID: Int32
        let processBirthSeconds: UInt64
        let processBirthMicroseconds: UInt64
        let socketDevice: Int32
        let socketInode: UInt64
        let codexHomePath: String
    }
    private final class Pending: @unchecked Sendable {
        let semaphore = DispatchSemaphore(value: 0)
        var response: Result<Data, Error>?
    }
    let runtimeVersion = CodexManagedRuntimeContract.version
    let supportsExecutionModes: Bool
    let instanceID: String
    private var notificationHandler: (@Sendable (String, Data) -> Void)?
    private var serverRequestHandler: (@Sendable (Data, String, Data) -> Bool)?
    var onNotification: (@Sendable (String, Data) -> Void)? {
        get {
            state.lock()
            defer { state.unlock() }
            return notificationHandler
        }
        set {
            state.lock()
            defer { state.unlock() }
            notificationHandler = newValue
        }
    }
    var onServerRequest: (@Sendable (Data, String, Data) -> Bool)? {
        get {
            state.lock()
            defer { state.unlock() }
            return serverRequestHandler
        }
        set {
            state.lock()
            defer { state.unlock() }
            serverRequestHandler = newValue
        }
    }
    private let proxy = Process()
    private let input = Pipe()
    private let output = Pipe()
    private let state = NSLock()
    private let writeLock = NSLock()
    private var pending: [Int: Pending] = [:]
    private var reverseRequests: Set<String> = []
    private var sequence = 0
    private var closed = false
    var connected: Bool {
        state.lock()
        defer { state.unlock() }
        return !closed && proxy.isRunning
    }
    private let reader = DispatchQueue(label: "vibepier.codex-managed-reader")
    private static let methods: Set<String> = [
        "initialize", "account/read", "thread/start", "thread/read", "turn/start", "turn/interrupt",
        "collaborationMode/list", "model/list", "thread/settings/update",
    ]

    init(configuration: CodexManagedRuntimeConfiguration) throws {
        guard configuration.enabled else { throw RuntimeDriverError.disabled }
        let executable = URL(fileURLWithPath: configuration.executablePath)
        let directory = URL(fileURLWithPath: configuration.directoryPath)
        guard configuration.executablePath.hasPrefix("/"), configuration.directoryPath.hasPrefix("/"),
            FileManager.default.isExecutableFile(atPath: executable.path),
            configuration.socketPath.utf8.count < 100
        else { throw RuntimeDriverError.invalidRequest }
        try RuntimePrivateStorage.ensureDirectory(directory)
        try RuntimePrivateStorage.ensureDirectory(URL(fileURLWithPath: configuration.codexHomePath))
        let version = try RuntimeSubprocess.capture(executable, arguments: ["--version"], timeout: 5)
        guard
            String(data: version, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
                == "codex-cli " + runtimeVersion
        else { throw RuntimeDriverError.incompatibleVersion }
        let schemas = FileManager.default.temporaryDirectory.appendingPathComponent(
            "vibepier-schema-" + UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: schemas) }
        _ = try RuntimeSubprocess.capture(
            executable,
            arguments: ["app-server", "generate-json-schema", "--out", schemas.path], timeout: 15)
        try CodexManagedRuntimeContract.validateSchemaDirectory(schemas, runtimeVersion: runtimeVersion)
        let experimental = schemas.appendingPathComponent("experimental")
        do {
            _ = try RuntimeSubprocess.capture(
                executable,
                arguments: ["app-server", "generate-json-schema", "--experimental", "--out", experimental.path],
                timeout: 15)
            try CodexManagedRuntimeContract.validateExecutionModeSchemaDirectory(
                experimental, runtimeVersion: runtimeVersion)
            supportsExecutionModes = true
        } catch {
            // Experimental drift disables only this capability. Never approximate it with a prompt.
            supportsExecutionModes = false
        }
        let lockFD = open(directory.appendingPathComponent("server.lock").path, O_RDWR | O_CREAT | O_NOFOLLOW, 0o600)
        guard lockFD >= 0 else { throw RuntimeDriverError.storageUnavailable }
        defer {
            _ = flock(lockFD, LOCK_UN)
            Darwin.close(lockFD)
        }
        guard flock(lockFD, LOCK_EX | LOCK_NB) == 0 else { throw RuntimeDriverError.unavailable }
        let metadataURL = directory.appendingPathComponent("server.json")
        let socketURL = URL(fileURLWithPath: configuration.socketPath)
        let metadata: Metadata
        if FileManager.default.fileExists(atPath: metadataURL.path) {
            guard
                let known = try? JSONDecoder().decode(
                    Metadata.self,
                    from: RuntimePrivateStorage.read(metadataURL, limit: 4096)),
                known.version == runtimeVersion, known.executablePath == executable.resolvingSymlinksInPath().path,
                known.codexHomePath == configuration.codexHomePath,
                Self.matchesProcess(known), Self.matchesSocket(socketURL, metadata: known)
            else { throw RuntimeDriverError.staleOwner }
            // No automatic replacement of an old socket or unverified process.
            metadata = known
        } else {
            guard !FileManager.default.fileExists(atPath: socketURL.path) else { throw RuntimeDriverError.staleOwner }
            let server = Process()
            server.executableURL = executable
            server.arguments = ["app-server", "--listen", "unix://" + socketURL.path]
            let inherited = ProcessInfo.processInfo.environment
            let allowed: Set<String> = [
                "PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TERM", "SHELL", "USER", "LOGNAME",
                "http_proxy", "https_proxy", "all_proxy", "no_proxy", "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
                "NO_PROXY",
            ]
            var environment = inherited.filter { allowed.contains($0.key) }
            environment["CODEX_HOME"] = configuration.codexHomePath
            server.environment = environment
            server.standardInput = FileHandle.nullDevice
            server.standardOutput = FileHandle.nullDevice
            server.standardError = FileHandle.nullDevice
            try server.run()
            let until = ProcessInfo.processInfo.systemUptime + 5
            while !Self.hasPrivateSocket(socketURL), server.isRunning,
                ProcessInfo.processInfo.systemUptime < until
            { Thread.sleep(forTimeInterval: 0.02) }
            var birth = proc_bsdinfo()
            var socketInfo = stat()
            guard server.isRunning, Self.hasPrivateSocket(socketURL),
                proc_pidinfo(
                    server.processIdentifier, PROC_PIDTBSDINFO, 0, &birth, Int32(MemoryLayout<proc_bsdinfo>.size))
                    == MemoryLayout<proc_bsdinfo>.size, lstat(socketURL.path, &socketInfo) == 0
            else {
                if server.isRunning { server.terminate() }
                throw RuntimeDriverError.unavailable
            }
            metadata = Metadata(
                version: runtimeVersion, instanceID: UUID().uuidString,
                executablePath: executable.resolvingSymlinksInPath().path, processID: server.processIdentifier,
                processBirthSeconds: birth.pbi_start_tvsec, processBirthMicroseconds: birth.pbi_start_tvusec,
                socketDevice: socketInfo.st_dev, socketInode: socketInfo.st_ino,
                codexHomePath: configuration.codexHomePath)
            do { try RuntimePrivateStorage.write(try JSONEncoder().encode(metadata), to: metadataURL) } catch {
                // Explicit startup failed before any client could submit a task.
                if server.isRunning { server.terminate() }
                throw error
            }
        }
        instanceID = metadata.instanceID
        proxy.executableURL = executable
        proxy.arguments = Array(configuration.sharedProxyArguments.dropFirst())
        proxy.standardInput = input
        proxy.standardOutput = output
        proxy.standardError = FileHandle.nullDevice
        for fd in [input.fileHandleForWriting.fileDescriptor, output.fileHandleForReading.fileDescriptor] {
            guard fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK) == 0 else { throw RuntimeDriverError.unavailable }
        }
        guard fcntl(input.fileHandleForWriting.fileDescriptor, F_SETNOSIGPIPE, 1) == 0 else {
            throw RuntimeDriverError.unavailable
        }
        try proxy.run()
        try input.fileHandleForReading.close()
        try output.fileHandleForWriting.close()
        reader.async { [weak self] in self?.readLoop() }
        do {
            var parameters: [String: Any] = ["clientInfo": ["name": "vibepier_managed", "version": "1"]]
            if supportsExecutionModes { parameters["capabilities"] = ["experimentalApi": true] }
            _ = try request("initialize", params: JSONSerialization.data(withJSONObject: parameters))
            try write(["method": "initialized", "params": [:] as [String: Any]])
        } catch {
            disconnect()
            throw error
        }
    }
    deinit { disconnect() }
    private static func hasPrivateSocket(_ url: URL) -> Bool {
        var info = stat()
        return lstat(url.path, &info) == 0 && info.st_uid == getuid()
            && (info.st_mode & S_IFMT) == S_IFSOCK && info.st_mode & 0o077 == 0
    }
    private static func matchesSocket(_ url: URL, metadata: Metadata) -> Bool {
        var info = stat()
        return hasPrivateSocket(url) && lstat(url.path, &info) == 0
            && info.st_dev == metadata.socketDevice && info.st_ino == metadata.socketInode
    }
    private static func matchesProcess(_ metadata: Metadata) -> Bool {
        var birth = proc_bsdinfo()
        var path = [UInt8](repeating: 0, count: 4096)
        guard
            proc_pidinfo(metadata.processID, PROC_PIDTBSDINFO, 0, &birth, Int32(MemoryLayout<proc_bsdinfo>.size))
                == MemoryLayout<proc_bsdinfo>.size,
            birth.pbi_uid == getuid(), birth.pbi_start_tvsec == metadata.processBirthSeconds,
            birth.pbi_start_tvusec == metadata.processBirthMicroseconds,
            proc_pidpath(metadata.processID, &path, UInt32(path.count)) > 0
        else { return false }
        return String(decoding: path.prefix(while: { $0 != 0 }), as: UTF8.self) == metadata.executablePath
    }
    func request(_ method: String, params: Data) throws -> Data {
        guard Self.methods.contains(method), params.count <= 280_000,
            let object = try JSONSerialization.jsonObject(with: params) as? [String: Any]
        else { throw RuntimeDriverError.invalidRequest }
        if ["collaborationMode/list", "model/list", "thread/settings/update"].contains(method), !supportsExecutionModes
        {
            throw RuntimeDriverError.unavailable
        }
        state.lock()
        guard !closed, pending.count < 16 else {
            state.unlock()
            throw RuntimeDriverError.unavailable
        }
        sequence += 1
        let id = sequence
        let waiter = Pending()
        pending[id] = waiter
        state.unlock()
        do { try write(["id": id, "method": method, "params": object]) } catch {
            state.lock()
            pending.removeValue(forKey: id)
            state.unlock()
            throw error
        }
        guard waiter.semaphore.wait(timeout: .now() + 15) == .success else {
            state.lock()
            pending.removeValue(forKey: id)
            state.unlock()
            throw RuntimeDriverError.timeout
        }
        state.lock()
        let response = waiter.response
        state.unlock()
        return try (response ?? .failure(RuntimeDriverError.unavailable)).get()
    }
    func respond(requestID: Data, result: Data) throws {
        guard requestID.count <= 300, result.count <= 280_000,
            let id = try? JSONSerialization.jsonObject(with: requestID, options: .fragmentsAllowed),
            let response = try? JSONSerialization.jsonObject(with: result) as? [String: Any]
        else { throw RuntimeDriverError.invalidRequest }
        let key = RuntimeOperationLedger.hash(requestID)
        state.lock()
        let accepted = !closed && reverseRequests.remove(key) != nil
        state.unlock()
        guard accepted else { throw RuntimeDriverError.staleOwner }
        try write(["id": id, "result": response])
    }
    func disconnect() {
        state.lock()
        guard !closed else {
            state.unlock()
            return
        }
        closed = true
        let waiters = Array(pending.values)
        pending.removeAll()
        for waiter in waiters {
            waiter.response = .failure(RuntimeDriverError.unavailable)
            waiter.semaphore.signal()
        }
        state.unlock()
        try? input.fileHandleForWriting.close()
        // Leave the read FD to its reader; shutdown the owned proxy to wake it.
        if proxy.isRunning { proxy.terminate() }
    }
    private func write(_ object: [String: Any]) throws {
        var data = try JSONSerialization.data(withJSONObject: object)
        guard data.count <= 300_000 else { throw RuntimeDriverError.invalidRequest }
        data.append(10)
        writeLock.lock()
        defer { writeLock.unlock() }
        let until = ProcessInfo.processInfo.systemUptime + 5
        try data.withUnsafeBytes { bytes in
            var offset = 0
            while offset < bytes.count {
                guard ProcessInfo.processInfo.systemUptime < until else { throw RuntimeDriverError.timeout }
                var descriptor = pollfd(
                    fd: input.fileHandleForWriting.fileDescriptor, events: Int16(POLLOUT), revents: 0)
                _ = poll(&descriptor, 1, 100)
                let count = Darwin.write(descriptor.fd, bytes.baseAddress!.advanced(by: offset), bytes.count - offset)
                if count < 0, [EINTR, EAGAIN, EWOULDBLOCK].contains(errno) { continue }
                guard count > 0 else { throw RuntimeDriverError.unavailable }
                offset += count
            }
        }
    }
    private func readLoop() {
        defer {
            try? output.fileHandleForReading.close()
            disconnect()
        }
        var buffer = Data()
        while true {
            state.lock()
            let shouldClose = closed
            state.unlock()
            if shouldClose { return }
            var descriptor = pollfd(fd: output.fileHandleForReading.fileDescriptor, events: Int16(POLLIN), revents: 0)
            let ready = poll(&descriptor, 1, 500)
            if ready == 0 { continue }
            if ready < 0, errno == EINTR { continue }
            guard ready > 0 else { return }
            var bytes = [UInt8](repeating: 0, count: 65536)
            let count = Darwin.read(descriptor.fd, &bytes, bytes.count)
            if count < 0, [EINTR, EAGAIN, EWOULDBLOCK].contains(errno) { continue }
            guard count > 0, buffer.count + count <= 8_388_608 else { return }
            buffer.append(contentsOf: bytes.prefix(count))
            while let end = buffer.firstIndex(of: 10) {
                let line = Data(buffer[..<end])
                buffer.removeSubrange(...end)
                guard let value = try? JSONSerialization.jsonObject(with: line) as? [String: Any] else { return }
                if let method = value["method"] as? String {
                    if let id = value["id"] {
                        var accepted = false
                        if [
                            "item/commandExecution/requestApproval", "item/fileChange/requestApproval",
                            "item/tool/requestUserInput",
                        ].contains(method),
                            let idJSON = try? JSONSerialization.data(withJSONObject: id, options: .fragmentsAllowed),
                            idJSON.count <= 300,
                            let params = value["params"],
                            let encoded = try? JSONSerialization.data(withJSONObject: params), encoded.count <= 280_000
                        {
                            let key = RuntimeOperationLedger.hash(idJSON)
                            state.lock()
                            let canAccept = reverseRequests.count < 32 && !reverseRequests.contains(key)
                            if canAccept { reverseRequests.insert(key) }
                            let callback = serverRequestHandler
                            state.unlock()
                            if canAccept { accepted = callback?(idJSON, method, encoded) == true }
                            if !accepted {
                                state.lock()
                                reverseRequests.remove(key)
                                state.unlock()
                            }
                        }
                        if !accepted {
                            try? write(["id": id, "error": ["code": -32601, "message": "Unsupported request"]])
                            if let params = value["params"],
                                let data = try? JSONSerialization.data(withJSONObject: params)
                            {
                                onNotification?("vibepier/unsupportedServerRequest", data)
                            }
                        }
                    } else if let parameters = value["params"],
                        let encoded = try? JSONSerialization.data(withJSONObject: parameters)
                    {
                        onNotification?(method, encoded)
                    }
                } else if let id = value["id"] as? Int {
                    state.lock()
                    if let waiter = pending.removeValue(forKey: id) {
                        if let result = value["result"],
                            let encoded = try? JSONSerialization.data(withJSONObject: result)
                        {
                            waiter.response = .success(encoded)
                        } else {
                            waiter.response = .failure(RuntimeDriverError.unavailable)
                        }
                        waiter.semaphore.signal()
                    }
                    state.unlock()
                }
            }
        }
    }
}

enum RuntimeSubprocess {
    static func capture(_ executable: URL, arguments: [String], timeout: TimeInterval) throws -> Data {
        let process = Process()
        let output = Pipe()
        process.executableURL = executable
        process.arguments = arguments
        process.standardInput = FileHandle.nullDevice
        process.standardOutput = output
        process.standardError = FileHandle.nullDevice
        let fd = output.fileHandleForReading.fileDescriptor
        _ = fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK)
        try process.run()
        try output.fileHandleForWriting.close()
        defer { try? output.fileHandleForReading.close() }
        let until = ProcessInfo.processInfo.systemUptime + timeout
        var data = Data()
        var eof = false
        while !eof || process.isRunning {
            guard ProcessInfo.processInfo.systemUptime < until else {
                if process.isRunning { process.terminate() }
                throw RuntimeDriverError.timeout
            }
            var descriptor = pollfd(fd: fd, events: Int16(POLLIN), revents: 0)
            _ = poll(&descriptor, 1, 20)
            var bytes = [UInt8](repeating: 0, count: 4096)
            let count = Darwin.read(fd, &bytes, bytes.count)
            if count == 0 { eof = true }
            if count < 0, ![EINTR, EAGAIN, EWOULDBLOCK].contains(errno) { throw RuntimeDriverError.unavailable }
            if count > 0 {
                guard data.count + count <= 8192 else {
                    process.terminate()
                    throw RuntimeDriverError.unavailable
                }
                data.append(contentsOf: bytes.prefix(count))
            }
        }
        guard process.terminationStatus == 0 else { throw RuntimeDriverError.unavailable }
        return data
    }
}
