#!/usr/bin/env python3
"""Generate shared session operation metadata. --check never rewrites sources."""
from pathlib import Path
import argparse
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "protocol/contracts/session-v1.json"
SWIFT = ROOT / "apps/macos/Sources/VibePierCore/Sessions/SessionV1Contract.generated.swift"
KOTLIN = ROOT / "apps/android/app/src/main/java/io/github/junweiup/vibepier/remote/core/session/SessionV1Contract.generated.kt"


def unique(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Duplicate contract key: {key}")
        result[key] = value
    return result


def generate():
    manifest = json.loads(SOURCE.read_text(), object_pairs_hook=unique)
    if manifest["version"] != 1 or type(manifest["version"]) is not int:
        raise ValueError("Expected current session contract version 1")
    canonical = json.dumps(manifest, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    digest = hashlib.sha256(canonical).hexdigest()
    operations = manifest["operations"]
    names = [entry["name"] for entry in operations]
    if len(names) != len(set(names)) or names != sorted(names):
        raise ValueError("Operations must have sorted unique names")
    fields = ["name", "routeDomain", "durableMutation", "uncertainOnTimeout", "providerPolicyExempt",
              "contentProviderScope", "laneCategory", "reconciliationKind", "capability", "cacheableRead"]
    bools = {"durableMutation", "uncertainOnTimeout", "providerPolicyExempt", "contentProviderScope", "cacheableRead"}
    domains = {"gateway", "session", "account", "control", "media"}
    for entry in operations:
        if set(entry) != set(fields) or not re.fullmatch(r"[a-z][a-zA-Z0-9]+", entry["name"]):
            raise ValueError(f"Invalid operation: {entry.get('name')}")
        if any(type(entry[field]) is not bool for field in bools):
            raise ValueError("Boolean contract fields must be JSON booleans")
        if entry["routeDomain"] not in domains or entry["laneCategory"] not in {"provider", "account", "controls"}:
            raise ValueError("Unknown route or admission lane")
        if entry["capability"] is not None and entry["capability"] not in manifest["capabilityKeys"]:
            raise ValueError("Unknown capability")
        if entry["durableMutation"] and not entry["uncertainOnTimeout"]:
            raise ValueError("Durable mutation must preserve timeout uncertainty")
    if manifest["providers"] != ["codex", "claude", "zcode"]:
        raise ValueError("Unexpected current provider inventory")
    if len(manifest["capabilityKeys"]) != len(set(manifest["capabilityKeys"])):
        raise ValueError("Duplicate capability")
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    swift = ["// Generated by scripts/dev/generate-session-contract.py. Do not edit.", "import Foundation", "",
             "enum SessionV1Contract {", f"    static let manifestSHA256 = {quote(digest)}",
             "    static let version = 1", "    static let capabilityVersion = 1",
             f"    static let providers = [{', '.join(map(quote, manifest['providers']))}]",
             "    static let capabilityKeys = [", *[f"        {quote(key)}," for key in manifest["capabilityKeys"]], "    ]",
             "    struct Operation: Sendable {", "        let name: String", "        let routeDomain: String",
             "        let durableMutation: Bool", "        let uncertainOnTimeout: Bool", "        let providerPolicyExempt: Bool",
             "        let contentProviderScope: Bool", "        let laneCategory: String", "        let reconciliationKind: String",
             "        let capability: String?", "        let cacheableRead: Bool", "    }",
             "    static let operations: [Operation] = ["]
    kotlin = ["// Generated by scripts/dev/generate-session-contract.py. Do not edit.",
              "package io.github.junweiup.vibepier.remote.core.session", "", "internal object SessionV1Contract {",
              f"    const val manifestSHA256 = {quote(digest)}", "    const val version = 1", "    const val capabilityVersion = 1",
              f"    val providers = listOf({', '.join(map(quote, manifest['providers']))})",
              f"    val capabilityKeys = listOf({', '.join(map(quote, manifest['capabilityKeys']))})",
              "    data class Operation(", "        val name: String, val routeDomain: String, val durableMutation: Boolean,",
              "        val uncertainOnTimeout: Boolean, val providerPolicyExempt: Boolean, val contentProviderScope: Boolean,",
              "        val laneCategory: String, val reconciliationKind: String, val capability: String?, val cacheableRead: Boolean",
              "    )", "    val operations: List<Operation> = listOf("]
    for entry in operations:
        def value(field, null):
            item = entry[field]
            if item is None:
                return null
            return str(item).lower() if type(item) is bool else quote(item)
        swift += ["        Operation("]
        swift += [f"            {field}: {value(field, 'nil')}" + ("," if index < len(fields) - 1 else "")
                  for index, field in enumerate(fields)]
        swift += ["        ),"]
        kotlin.append("        Operation(" + ", ".join(value(field, "null") for field in fields) + "),")
    swift += ["    ]", "    private static let byName = Dictionary(uniqueKeysWithValues: operations.map { ($0.name, $0) })",
              "    static func descriptor(_ operation: String) -> Operation? { byName[operation] }", "}", ""]
    kotlin += ["    )", "    private val byName = operations.associateBy { it.name }",
               "    fun operation(name: String): Operation? = byName[name]", "}", ""]
    return {SWIFT: "\n".join(swift), KOTLIN: "\n".join(kotlin)}, manifest, digest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs, manifest, digest = generate()
    for path, output in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != output:
                raise SystemExit(f"Stale generated contract: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(output)
    print(f"{'PASS' if args.check else 'Generated'}: {len(manifest['operations'])} shared session operations ({digest[:12]})")


if __name__ == "__main__":
    main()
