#!/usr/bin/env python3
"""Generate the embedded Mac catalog; --check verifies the checked-in source without changing it."""
from pathlib import Path
import argparse
import json
import re

root = Path(__file__).resolve().parents[2]
source = root / 'apps/macos/Localization/Strings.json'
destination = root / 'apps/macos/Sources/VibeLocalization/LocalizationCatalog.swift'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()

def unique(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'Duplicate catalog key: {key}')
        result[key] = value
    return result

entries = json.loads(source.read_text(), object_pairs_hook=unique)
def placeholders(value):
    return {int(index) for index in re.findall(r'\{([0-9]+)\}', value)}

def swift(value):
    if any(ord(char) < 32 and char not in '\n\r\t' for char in value):
        raise ValueError('Unsupported control character in catalog')
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t') + '"'

lines = [
    '// Generated by scripts/dev/localize-macos.py from apps/macos/Localization/Strings.json.',
    '// Edit the catalog, then regenerate. Both locales are embedded for standalone CLI distribution.',
    'enum LocalizationCatalog {',
    '    static let entries: [String: [String]] = [',
]
for key, translated in sorted(entries.items()):
    if not re.fullmatch(r'[a-z][a-z0-9_.]+', key) or set(translated) != {'en', 'zh-Hans'}:
        raise ValueError(f'Invalid key or missing locale: {key}')
    en, zh = translated['en'], translated['zh-Hans']
    if not isinstance(en, str) or not isinstance(zh, str) or not en or not zh:
        raise ValueError(f'Empty/non-text translation: {key}')
    fields = placeholders(en)
    if fields != placeholders(zh) or fields != set(range(len(fields))):
        raise ValueError(f'Placeholder contract differs or is not contiguous: {key}')
    lines += [f'        {swift(key)}: [', f'            {swift(en)},', f'            {swift(zh)},', '        ],']
lines += ['    ]', '}', '']
result = '\n'.join(lines)
for path in (root / 'apps/macos/Sources').rglob('*.swift'):
    for key in re.findall(r'L10n\.text\(\s*"([^"]+)"', path.read_text()):
        if key not in entries:
            raise ValueError(f'Missing catalog key {key} in {path.relative_to(root)}')
if args.check:
    if not destination.exists() or destination.read_text() != result:
        raise SystemExit('Mac localization source is stale. Run python3 scripts/dev/localize-macos.py')
    print(f'PASS: {len(entries)} embedded English/zh-Hans Mac catalog entries and placeholder contracts')
else:
    destination.write_text(result)
    print(f'Generated {len(entries)} embedded Mac catalog entries')
