// Generated by scripts/dev/generate-session-contract.py. Do not edit.
package io.github.junweiup.vibepier.remote.core.session

internal object SessionV1Contract {
    const val manifestSHA256 = "d2bf4da49fde72731f73cbe740917b55b1eb5af1dce2cb59a062fde4060bef47"
    const val version = 1
    const val capabilityVersion = 1
    val providers = listOf("codex", "claude")
    val capabilityKeys = listOf("approvals", "attachments", "contextUsage", "effortSelection", "executionMode", "interrupt", "markdownFiles", "modelSelection", "new", "newAttachments", "permissionMode", "projectFiles", "questions", "queue", "queueDelete", "queueSteer", "send", "settings", "videoFiles")
    data class Operation(
        val name: String, val routeDomain: String, val durableMutation: Boolean,
        val uncertainOnTimeout: Boolean, val providerPolicyExempt: Boolean, val contentProviderScope: Boolean,
        val laneCategory: String, val reconciliationKind: String, val capability: String?, val cacheableRead: Boolean
    )
    val operations: List<Operation> = listOf(
        Operation("androidUpdateStage", "gateway", false, true, true, false, "controls", "", null, false),
        Operation("apkBinary", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("apkOffer", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("apkProgress", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("apkStatus", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("appUsage", "gateway", false, false, true, false, "controls", "", null, false),
        Operation("appUsageSet", "gateway", false, false, true, false, "controls", "", null, false),
        Operation("appVersion", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("applicationShortcutSet", "control", false, false, true, false, "controls", "", null, false),
        Operation("applications", "control", false, false, true, false, "controls", "", null, false),
        Operation("approvalDetails", "session", false, false, false, true, "provider", "", null, true),
        Operation("approve", "session", true, true, false, true, "provider", "receiptCheck", "approvals", false),
        Operation("appshot", "session", false, false, false, true, "provider", "", null, false),
        Operation("appshotApps", "session", false, false, false, true, "provider", "", null, false),
        Operation("attachmentComplete", "session", false, false, false, true, "provider", "", "attachments", false),
        Operation("attachmentPreview", "session", false, false, false, true, "provider", "", "attachments", false),
        Operation("attachmentReference", "session", false, false, false, true, "provider", "", "attachments", false),
        Operation("attachmentRemove", "session", false, false, false, true, "provider", "", "attachments", false),
        Operation("attachmentStart", "session", false, false, false, true, "provider", "", "attachments", false),
        Operation("browseFiles", "session", false, false, false, true, "provider", "", "projectFiles", true),
        Operation("close", "session", false, false, true, false, "provider", "", null, false),
        Operation("codexUsage", "account", false, false, false, true, "account", "", null, false),
        Operation("codexUsageReset", "account", true, true, false, true, "account", "codexUsageResetReceipt", null, false),
        Operation("codexUsageResetReceipt", "account", false, false, true, false, "account", "", null, false),
        Operation("composerOptions", "session", false, false, false, true, "provider", "", "settings", true),
        Operation("contextUsage", "session", false, false, false, true, "provider", "", "contextUsage", true),
        Operation("fileCancel", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("fileChanges", "session", false, false, false, true, "provider", "", "projectFiles", true),
        Operation("fileDiff", "session", false, false, false, true, "provider", "", "projectFiles", true),
        Operation("history", "session", false, false, false, true, "provider", "", null, true),
        Operation("image", "session", false, false, false, true, "provider", "", null, true),
        Operation("interrupt", "session", true, true, false, true, "provider", "interruptReceiptCheck", "interrupt", false),
        Operation("interruptReceiptCheck", "session", false, false, true, false, "provider", "", null, false),
        Operation("list", "session", false, false, false, true, "provider", "", null, true),
        Operation("lockScreen", "control", true, true, true, false, "controls", "", null, false),
        Operation("message", "session", false, false, false, true, "provider", "", null, true),
        Operation("new", "session", true, true, false, true, "provider", "newReceiptCheck", "new", false),
        Operation("newAttachmentComplete", "session", false, false, false, true, "provider", "", "newAttachments", false),
        Operation("newAttachmentRemove", "session", false, false, false, true, "provider", "", "newAttachments", false),
        Operation("newAttachmentStart", "session", false, false, false, true, "provider", "", "newAttachments", false),
        Operation("newOptions", "session", false, false, false, true, "provider", "", "new", false),
        Operation("newReceiptCheck", "session", false, false, true, false, "provider", "", null, false),
        Operation("notificationSubscribe", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("open", "session", false, false, false, true, "provider", "", null, false),
        Operation("openFile", "session", false, false, false, true, "provider", "", "projectFiles", false),
        Operation("parts", "session", false, false, false, true, "provider", "", null, true),
        Operation("projects", "session", false, false, false, true, "provider", "", null, true),
        Operation("providers", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("queueDelete", "session", true, true, false, true, "provider", "queueReceiptCheck:delete", "queueDelete", false),
        Operation("queueReceiptCheck", "session", false, false, true, false, "provider", "", null, false),
        Operation("queueSteer", "session", true, true, false, true, "provider", "queueReceiptCheck:steer", "queueSteer", false),
        Operation("readFile", "session", false, false, false, true, "provider", "", "projectFiles", true),
        Operation("readImageFile", "session", false, false, false, true, "provider", "", "projectFiles", true),
        Operation("readMarkdownFile", "session", false, false, false, true, "provider", "", "markdownFiles", true),
        Operation("readVideoFile", "session", false, false, false, true, "provider", "", "videoFiles", true),
        Operation("receipt", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("receiptCheck", "session", false, false, true, false, "provider", "", null, false),
        Operation("relaySetup", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("resend", "gateway", false, false, true, false, "provider", "", null, false),
        Operation("searchFiles", "session", false, false, false, true, "provider", "", "projectFiles", true),
        Operation("send", "session", true, true, false, true, "provider", "receiptCheck", "send", false),
        Operation("settings", "session", true, true, false, true, "provider", "settingsReceiptCheck", "settings", false),
        Operation("settingsReceiptCheck", "session", false, false, true, false, "provider", "", null, false),
        Operation("sync", "session", false, false, false, true, "provider", "", null, true),
        Operation("unlockPassword", "control", false, true, true, false, "controls", "", null, false),
        Operation("unlockScreen", "control", true, true, true, false, "controls", "", null, false),
        Operation("unlockStatus", "control", false, false, true, false, "controls", "", null, false),
    )
    private val byName = operations.associateBy { it.name }
    fun operation(name: String): Operation? = byName[name]
}
